### ISSUE TITLE
[Help] Copy & pasting

### ISSUE THREAD

**Issue by TiriaAndersen** [samuelivarsson/atom-iv-terminal#1]
Windows 10, Atom ver. 7.4, iv-terminal 1.3.0
Default Shell

Copying & pasting via the command pallet works fine,
but highlighting output and copying via Ctrl+c on the terminal directly is interpreted as break command, and doesn't copy.
![image](https://user-images.githubusercontent.com/15015814/76282718-39340f00-62e4-11ea-8ba4-bb6e84529e32.png)

Likewise Ctrl+v directly in the terminal just gives ^V:
![image](https://user-images.githubusercontent.com/15015814/76282611-e6f2ee00-62e3-11ea-8ec0-52938178beae.png)

While I could just do it via the command pallette every time, is there any way to directly copy & paste in the terminal?

**Comment by samuelivarsson** [comment]
Sorry for the extremely late answer, but I'll post it anyways for reference. 

I figured the best solution would be to change the keymaps for the copy and paste command, since you want to be able to use the break command. I therefore updated the default keymaps for copying and pasting on windows and linux in version 1.3.1. Now you can copy with "ctrl+insert" and paste with "shift+insert", just as you would in command prompt.

**Comment by nelson6e65** [comment]
I think `ctrl-shift-c/v` it is more intuitive and similar to other terminals.

I disabled default keymap, and customize my `keymap.cson`:

```cson
'terminal-view':
  'ctrl-shift-c': 'iv-terminal:copy'
  'ctrl-shift-v': 'iv-terminal:paste'
```

BTW, in the original package I was unable to copy/paste. Nice to have it here. Thanks. @samuelivarsson  😀
